/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Adoption.BGCandCriminalCheck;

import Business.Adopter.Adopter;
import Business.Adopter.AdopterDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.BackgroundAndCriminalCheckOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BGCWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehaswaroop
 */
public class BGCandCriminalCheckRequestTable extends javax.swing.JPanel {

    /**
     * Creates new form BGCandCriminalCheckRequestTable
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem business;
    AdopterDirectory udirectory;
    BackgroundAndCriminalCheckOrganization bgcOrganization;
    Adopter adopter;
    
    public BGCandCriminalCheckRequestTable(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, AdopterDirectory udirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.udirectory=udirectory;
        this.account=account;
        this.enterprise=enterprise;
        this.business = business;
        this.bgcOrganization = (BackgroundAndCriminalCheckOrganization)organization;
//        valueLabel.setText(enterprise.getName());
//        orgLabel.setText(organization.getName());
        this.adopter = adopter;
        
        populateWorkRequest();
    }
    
    public void populateWorkRequest(){
      
        DefaultTableModel dtm = (DefaultTableModel)tblRequest.getModel();
            dtm.setRowCount(0);
        for (WorkRequest request : bgcOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof BGCWorkRequest){
           Object[] row = new Object[dtm.getColumnCount()];
           row[0]= request;
           row[1]= request.getSender().getEmployee().getName();
           row[2]= request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
           row[3] = request.getUserId();
           //row[4] = request.getReceiver();
           row[5] = request.getStatus();
            dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("BACKGROUND AND CRIMINAL CHECK REQUESTS");
        add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 57, 511, -1));

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "UserID", "Adopter Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 870, 140));

        btnAssign.setText("ASSIGN TO ME");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 160, 30));

        btnProcess.setText("PROCESS");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a workrequest");
            return;
        }
        Object receiverval =  tblRequest.getValueAt(selectedRow, 2);
        Object statusval =  tblRequest.getValueAt(selectedRow, 4);
        
        
        if(statusval.equals("Pending with BGC organization")){
        WorkRequest re = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);
        re.setReceiver(account);
        re.setStatus("BGC organization processing");
        populateWorkRequest();
        }
        else{
        //if(statusval.equals("Approved")||statusval.equals("Denied"))
        if("Approved".equals(statusval) || "Denied".equals(statusval))
            JOptionPane.showMessageDialog(null,"Please select some other request,this work request is already processed");
//        else if(!receiverval.equals(account.getUsername()))
//            JOptionPane.showMessageDialog(null,"Work request is assigned to someone else");
//        else if(receiverval.equals(account.getUsername()))
//            JOptionPane.showMessageDialog(null,"Work request is already assigned to you");
        } 
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a workrequest");
            return;
        }
        WorkRequest req = (WorkRequest) tblRequest.getValueAt(selectedRow, 0);
        Object receiverval =  tblRequest.getValueAt(selectedRow, 2);
        Object statusval =  tblRequest.getValueAt(selectedRow, 4);
        for(Adopter a: udirectory.getAdoptersList()){
            if(a.getUserId()==req.getUserId()){
                adopter=a;
            }
        }
        if(receiverval==null){
            JOptionPane.showMessageDialog(null,"Please first assign it to yourself");
        }
        
        
        else{
        if( receiverval.equals(account.getUsername()) && statusval.equals("BGC organization processing")){
        BGCandCriminalProcess panel = new BGCandCriminalProcess(userProcessContainer,account, bgcOrganization, enterprise, business, udirectory,(BGCWorkRequest) req, adopter);
        this.userProcessContainer.add("BackgroundAndCriminalCheckProcessRequestJPanel", panel);
        CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);}
        else if(statusval.equals("Approved")|| statusval.equals("Denied"))
            JOptionPane.showMessageDialog(null,"The selected workrerequest is already processed");
        else if(!receiverval.equals(account.getUsername()))
            JOptionPane.showMessageDialog(null,"Please select the work request assigned to you to proceed");
        } 
    }//GEN-LAST:event_btnProcessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JTable tblRequest;
    // End of variables declaration//GEN-END:variables
}
