/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterCare.ChildRegistrationRole;

import Business.Child.Child;
import Business.Child.ChildDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ChildRegistrationOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snehaswaroop
 */
public class ViewChildTable extends javax.swing.JPanel {

    /**
     * Creates new form ChildRegistrationWorkAreaPanel
     */
    //Attributes though which the data will flow
    JPanel userProcessContainer;
    UserAccount account;
    ChildRegistrationOrganization childRegistrationOrganization;
    Enterprise enterprise;
    Child child;
    ChildDirectory directory;
    EcoSystem business;
    Network network;
    //ChildDirectory anewdir =  this.business.getChildDirectory();

    public ViewChildTable(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, ChildDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.childRegistrationOrganization = (ChildRegistrationOrganization) organization;
        this.business = business;
        this.directory = directory;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());

        valueLabel1.setText(childRegistrationOrganization.getName());

        for (Network net : business.getNetworkList()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                if (ent.equals(enterprise)) {
                    network = net;
                }
            }
        }

        poplulateTable();
//        populateChildRequestTable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNewChild = new javax.swing.JTable();
        btnViewChild = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnDeleteChild = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNewChild.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child Id", "Child Name", "Gender", "Age", "Status", "Medical Status", "Assigned Doctor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNewChild);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 870, 100));

        btnViewChild.setText("View Child Details");
        btnViewChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewChildActionPerformed(evt);
            }
        });
        add(btnViewChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 150, 33));

        enterpriseLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel.setText("ORGANISATION");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 27, 180, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 150, 30));

        btnDeleteChild.setText("Delete Child");
        btnDeleteChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteChildActionPerformed(evt);
            }
        });
        add(btnDeleteChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 150, 33));

        enterpriseLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Enterprise");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 127, 30));

        valueLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel1.setText("<value>");
        add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 150, 26));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transparentKids.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 480, 330));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refreshIcon.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/childLogo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewChildActionPerformed
        
        /*This set of code will take the UI to the vie child details*/
        int selectedRow = tblNewChild.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a child to view details");
            return;
        }
        
        child = (Child)tblNewChild.getValueAt(selectedRow, 0);
             
        ViewChildDetailsJPanel viewChildJpanel = new ViewChildDetailsJPanel(userProcessContainer, child);
       this.userProcessContainer.add("ViewChildDetailsJPanel", viewChildJpanel);
       CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewChildActionPerformed

    private void btnDeleteChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteChildActionPerformed
    int selectedRow = tblNewChild.getSelectedRow();
       if(selectedRow<0){
           JOptionPane.showMessageDialog(null, "Please select a child to delete");
       }
       Child ch = (Child) tblNewChild.getValueAt(selectedRow, 0);
       int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the child?", "Alert", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == 0) {
            directory.removeChild(ch);
            List<Organization> list = new ArrayList<>();
            for (Network network : business.getNetworkList()) {
                // getNetworkList().getOrganizationDirectory().getOrganizationList()
                System.out.println("network: " + network);
                for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (this.network.equals(network)) {
                        for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {

                            if (organization instanceof DoctorOrganization || organization instanceof PharmacistOrganization || organization instanceof LabOrganization) {

                                list.add(organization);
                            }
                        }
                    }

                }
            }
            
            for (Organization org : list) {
                org.getWorkQueue().delete(ch.getChildId());
            }
            account.getWorkQueue().delete(ch.getChildId());
            business.getWorkQueue().delete(ch.getChildId());
        }
        poplulateTable();
       
    }//GEN-LAST:event_btnDeleteChildActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        poplulateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

/*Method to populate the table of with child details*/    
    public void poplulateTable(){
      
        DefaultTableModel dtms = (DefaultTableModel)tblNewChild.getModel();
           dtms.setRowCount(0);
       if(directory!=null && directory.getChildList()!=null && directory.getChildList().size()>0){
           for(Child child : directory.getChildList()){
            Object[] row = new Object[dtms.getColumnCount()];
            row[0] = child;
            row[1]=child.getName();
            row[2]=child.getGender();
            row[3]=child.getChildAge();
            row[4]=child.getStatus();
            dtms.addRow(row);
        
        }
       }
        
    }
    /*Method to populate the table with work request that has been created for the doctor*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteChild;
    private javax.swing.JButton btnViewChild;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNewChild;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
}
