/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterCare.ChildCare;

import Business.Adopter.Adopter;
import Business.Adopter.AdopterDirectory;
import Business.Child.Child;
import Business.Child.ChildDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ChildCareOrganization;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ChildCareAdoptionWorkRequest;
import Business.WorkQueue.ChildCareWorkRequest;
//import Business.WorkQueue.ChildCareAdoptionWorkRequest;
//import Business.WorkQueue.ChildCareWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 12013
 */
public class ChildCareWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChildCareWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    UserAccount account;
    ChildCareOrganization childCareOrganization;
    ChildDirectory directory;
    Child child;
    EcoSystem business;
    ChildCareWorkAreaJPanel panel;
    AdopterDirectory udirectory;
    Adopter adopter;
    Role roler;
    Network network;
      
    public ChildCareWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, ChildDirectory directory, AdopterDirectory udirectory) {
     initComponents();
    this.userProcessContainer=userProcessContainer;
    this.account=account;
    this.business = business;
    this.childCareOrganization=(ChildCareOrganization)organization;
    this.directory = directory;
    this.udirectory = udirectory;
    
         System.out.println("directory; "+directory.toString());
    this.enterprise=enterprise;
         valueLabel.setText(enterprise.getName());
         orgLabel.setText(childCareOrganization.getName());
        processBtn.setEnabled(false);
    
        for(Network net: business.getNetworkList()){
      for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
          if(ent.equals(enterprise)){
              network= net;
          }
      }
  }
        
         populateAdopterTable();
         populateChildTable();
         populateWorkRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblOrganization = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        orgLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        childTable = new javax.swing.JTable();
        viewChildBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrganization.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOrganization.setText("Organization :");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 127, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 158, 30));

        orgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orgLabel.setText("<value>");
        add(orgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 133, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Child Health Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 113, 130, 24));

        workTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Doctor Name", "CC Admin", "Child ID", "Status", "Child Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 143, 560, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Child details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 360, 93, 24));

        childTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child ID", "Child Name", "Age", "Gender", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(childTable);
        if (childTable.getColumnModel().getColumnCount() > 0) {
            childTable.getColumnModel().getColumn(0).setResizable(false);
            childTable.getColumnModel().getColumn(1).setResizable(false);
            childTable.getColumnModel().getColumn(2).setResizable(false);
            childTable.getColumnModel().getColumn(3).setResizable(false);
            childTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 402, 523, 89));

        viewChildBtn.setText("View Child Details");
        viewChildBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewChildBtnActionPerformed(evt);
            }
        });
        add(viewChildBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 143, 33));

        processBtn.setText("Process Request");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 251, 133, 33));

        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 251, 133, 33));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Child Id", "Child Name", "Adopter ID", "Adopter Name", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 143, -1, 90));

        jButton1.setText("Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 251, 133, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Adopter Request");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 113, 105, 24));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/FosterCare/ChildCare/1577868739464.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 350, 180));

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEnterprise.setText("EnterPrise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 127, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        int selectedRow = workTable.getSelectedRow();
       if(selectedRow<0){
           JOptionPane.showMessageDialog(null, "Please select a request"); 
           return;
       }
       WorkRequest re = (WorkRequest) workTable.getValueAt(selectedRow, 0);
      
        
       for(Child ch : directory.getChildList()){

           if(ch.getChildId()==re.getChildId()){

               child=ch;
           
           }
       }
       
//    pjpj    ProcessChildCareWorkRequest pccwr = new ProcessChildCareWorkRequest(userProcessContainer, organization, (ChildCareWorkRequest) re, directory, child, account, business);
//        this.userProcessContainer.add("ProcessChildCareWorkRequest", pccwr);
       CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_processBtnActionPerformed

    private void viewChildBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewChildBtnActionPerformed
      int selectedRow = childTable.getSelectedRow();
    
      
      if(selectedRow<0){
           JOptionPane.showMessageDialog(null, "Please select a child");
          return;
      }
      
          Child child = (Child) childTable.getValueAt(selectedRow, 0);      
        
       
        ViewCompleteChildDetails completeJapanel = new ViewCompleteChildDetails(userProcessContainer,account,organization,enterprise,business,directory, child);
       this.userProcessContainer.add("ViewCompleteChildDetails", completeJapanel);
       CardLayout layout = (CardLayout)this.userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_viewChildBtnActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
       int selectedRow = workTable.getSelectedRow();
       if(selectedRow<0){
           JOptionPane.showMessageDialog(null, "Please select a request");
           return;
       }
       WorkRequest re = (WorkRequest) workTable.getValueAt(selectedRow, 0);
       re.setReceiver(account);
       re.setStatus("Pending with child care");
       populateWorkRequest();
        processBtn.setEnabled(true);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow<0){
             JOptionPane.showMessageDialog(null, "Please select a request");
            return;
        }
       
        ChildCareAdoptionWorkRequest req = (ChildCareAdoptionWorkRequest) jTable1.getValueAt(selectedRow, 0);
        req.setStatus("Approved");
        for(Child ch: directory.getChildList()){
            if(ch.getChildId()==req.getChildId()){
                ch.setStatus("Adopted by "+req.getUserName());
            }
        }
        
        
        
        populateAdopterTable();
    }//GEN-LAST:event_jButton1ActionPerformed
public void populateChildTable(){

    DefaultTableModel dtms = (DefaultTableModel)childTable.getModel();
    dtms.setRowCount(0);
    for(Child ch : directory.getChildList()){
        
   if(ch.getStatus().equalsIgnoreCase("Acquired") || ch.getStatus().startsWith("Adopted by")){
//    pjpj      Object[] row = new Object[dtms.getColumnCount()];
//          row[0]=ch;
//          row[1]=ch.getChildname();
//          row[2]=ch.getChildAge();
//          row[3]=ch.getChildGender();
//          row[4]=ch.getStatus();
//          
//          dtms.addRow(row);
        }
    }
}

public void populateWorkRequest(){
    
    
    DefaultTableModel dtms = (DefaultTableModel)workTable.getModel();
       dtms.setRowCount(0);
    for(WorkRequest req : childCareOrganization.getWorkQueue().getWorkRequestList()){
     
       if(req instanceof ChildCareWorkRequest){
           
          Object[] row = new Object[dtms.getColumnCount()];
          row[0]=req;
          row[1]=req.getSender();
          row[2]=req.getReceiver();
          row[3]=req.getChildId();
          row[4]=req.getStatus();
          
          dtms.addRow(row);
           }
        
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JTable childTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel orgLabel;
    private javax.swing.JButton processBtn;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewChildBtn;
    private javax.swing.JTable workTable;
    // End of variables declaration//GEN-END:variables

    public void populateAdopterTable(){
        DefaultTableModel dtms = (DefaultTableModel) jTable1.getModel();
        dtms.setRowCount(0);
        for(WorkRequest req: business.getWorkQueue().getWorkRequestList()){
            if(req instanceof ChildCareAdoptionWorkRequest){

                
                    Object[] row = new Object[dtms.getColumnCount()];
                    row[0]=req;
                    row[1]=req.getChildId();
                    row[2]= ((ChildCareAdoptionWorkRequest) req).getUserName();
                    row[3]= req.getStatus();
                    dtms.addRow(row);
                }
            
        }
        
    }
    
    

}
